const eventTypes = {
  FEATURE_UPDATE: "FEATURE_UPDATE",
  FEATURE_UPDATES: "FEATURE_UPDATES",

  UPDATE_FEATURE: "UPDATE_FEATURE",
  CREATE_FEATURE: "CREATE_FEATURE",
  DELETE_FEATURE: "DELETE_FEATURE",
  ALL_FEATURES: "ALL_FEATURES"
}

module.exports = eventTypes;